### ISSUE TITLE
GIN/GUICE replacement

### ISSUE THREAD

**Issue by justinmk** [mvp4g/mvp4g#126]
In your [GWT group post](https://groups.google.com/forum/#!topic/mvp4g/XNuQGpbvZp8) you mentioned:

> remove the dependency to GIN and GUICE

What do you plan to replace it with? Is there a discussion about this somewhere?

Thanks.

**Comment by FrankHossfeld** [comment]
First of all, the current mvp4g implementation will offer a long term support for GWT 2.x.

Beside that we have started implementing a new version. That version will be called mvp4g3 and will support GWT 3 and hopefully will work with GWT 2.x. Also this project will drop/replace some features of the mvp4g implementation. 

At the moment the project is private because the state is so early and we checking several third party libs.  At the moment we use JavaPoet for generating the source files, guava, Google auto-service and dagger 2 to replace GIN.   

I am not sure, if we will replace GIN/GUICE in this mvp4g project as long as it works.

Do you have any impacts related to GIN?

**Comment by justinmk** [comment]
> At the moment we use JavaPoet for generating the source files, guava, Google auto-service and dagger 2 to replace GIN.

All of those are the replacement for GIN? Or only auto-service + dagger 2?

> I am not sure, if we will replace GIN/GUICE in this mvp4g project as long as it works.

Our project makes heavy use of GIN, so I got spooked by your post which mentioned "GWT 3 will remove generators". I'm trying to find discussion or references on this, I hope it's not too off-topic.

**Comment by FrankHossfeld** [comment]
Sorry, we will use dagger 2 to replace GIN.

As far as I know, you can use dagger 2 and GIN together. It should work. But looking forward to GWT 3 I think, GIN has also to replace the generators by annotation processors. 

Take a look here:
https://groups.google.com/forum/#!topic/google-web-toolkit/WEje9KW7Iy4

and the things Ray said:
https://www.youtube.com/watch?v=ltqWRoJ0S-o&list=PL1yReUCGwGvrqscLu1EAyYRPrr0ceEHLE

Also I talked to Danial Kurka at the GWT.create 2015. He also told me, that GWT will replace generators and that it should be a good idea to use annotations processors instead.

**Comment by justinmk** [comment]
Thanks a lot for your help.
